name: 'Validate, Build, Test and Deploy'
description: 'Validate, Build, Test and Deploy python poetry project'

runs:
  using: "composite"
  steps:

    # Build
    - name: Validate input schema's
      run: |
          poetry run ./nornir/nr_validate_schema.py
    - name: Generate device config
      run: |
          mkdir -p nornir/output/ ;
          poetry run ./nornir/nr_build_config.py
