name: 'Validate, Build, Test and Deploy'
description: 'Validate, Build, Test and Deploy python poetry project'

runs:
  using: "composite"
  steps:

    # Build
    - name: Validate input schema's
      shell: bash
      run: |
          poetry run ./nornir/nr_validate_schema.py
    - name: Generate device config
      shell: bash
      run: |
          mkdir -p nornir/output/ ;
          poetry run ./nornir/nr_build_config.py
    - uses: actions/upload-artifact@v3
      with:
        name: generated-configs
        path: nornir/output